### ISSUE TITLE
CRAN installation doesn't work with R 3.6.0

### ISSUE THREAD

**Issue by kant97** [IOHprofiler/IOHanalyzer#17]
Hello! I am trying to install IOHanalyzer locally as R package. I use this command: [https://github.com/IOHprofiler/IOHanalyzer/blob/master/README.md#-using-iohprofiler-as-a-r-package](url), but I get the following message and installation fails.

```text
Warning message:
package ‘IOHanalyzer’ is not available (for R version 3.6.0)
```

My `sessionInfo()` is:

```text
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=ru_RU.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=ru_RU.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=ru_RU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=ru_RU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0
```

**Comment by Dvermetten** [comment]
Dear Kirill,

Thank you for this issue report. We are aware of some issues with the CRAN-version of our package, and are working to resolve this with them. Currently, IOHanalyzer is not available on CRAN anymore until this is fixed, so we would recommend to use devtools to install the package instead ([Installing the package using devtools](https://github.com/IOHprofiler/IOHanalyzer#installing-the-developement-version)). 
We are sorry for the inconvenience, and will let you know when the package is available on CRAN again.

Best regards,
Diederick

**Comment by Dvermetten** [comment]
Dear Kirill,

The IOHanalyzer is back on CRAN, so the standard installation ( install.packages('IOHanalyzer') ) should now be working again.

Best regards,
Diederick
