### ISSUE TITLE
"Remove all the data" does not really remove anything

### ISSUE THREAD

**Issue by mbuzdalov** [IOHprofiler/IOHanalyzer#19]
Assume I have uploaded an archive, say, `data.zip`, with files `file1.info` and `file1.dat`.

Next I press "Remove all the data" and upload an archive with **the same name** `data.zip` but different contents **with different file names**, e.g. `file2.info` and `file2.dat`.

After that, the profiler processes the new files **as well as** (mistakenly) the old files, which have remained at the server in the temporary directories.

I think this should not happen, e.g. "Remove all the data" shall also mean "I don't want to see the removed data in the analysis any more".

**Comment by wangronin** [comment]
Thank you for reporting this! believe this issue is fixed in the latest commit.
