### ISSUE TITLE
Some thoughts on funcId, instance number, ...

### ISSUE THREAD

**Issue by thomasWeise** [IOHprofiler/IOHanalyzer#37]
Hi.

I am currently looking into the data format used by the IOHanalyzer and profiler.

It first seemed to me that the function ID can be any string.
For example, in https://iohprofiler.github.io/IOHanalyzer/data/#raw-data, we call it "`IOHprofiler_f[function ID]_DIM_[dimension]_i[instance number]`", i.e., "function ID" vs. instance number and later it is stated "`Three keys, funcId, DIM, and algId are case-sensitive and mandatory.`"
So if it is case-sensitive, an arbitrary string should be allowed (although that may not make much sense for `DIM`).

However, under http://iohprofiler.liacs.nl/#shiny-tab-dataformat, i.e., when clicking "Data Format", it states "`IOHprofiler_f[:num:]_i[:num:].info`", so there, the function Id is clearly a number.
When scrolling a bit through the code of the IOHanalyzer, I find stuffs such as [`cat(sprintf('Function ID: %d\n', ds_attr$funcId))`](https://github.com/IOHprofiler/IOHanalyzer/blob/master/R/DataSet.R) and [`arrange(dsl, DIM, -funcId, algId)`](https://github.com/IOHprofiler/IOHanalyzer/blob/master/R/DataSetList.R), so this seems to indicate numeric function IDs and/or could explode if we feed in strings.

From my perspective, I would very much like to have string function Ids.
Why?
If you have widely diverse function sets, say including OneMax, TwoMax, LeadingOnes, MaxSat, VertexCover, KnappSack, NQueens and what not, numeric function IDs are just confusing.
Numeric IDs make a lot of sense if you have a fixed and never changing set of benchmark functions.
But if I understand correctly, the purpose of IOH is exactly not that and instead it offers an environment where we can plug in new functions and problems.

I would much rather have "OneMax" as string with dimension 100, for example, instead of f7 with dimension 100.
This problem also becomes apparent when checking the [PBO benchmark suite](https://iohprofiler.github.io/Suites/PBO/): The function IDs F1 ... F23 do not carry much information. In order to understand them, it is absolutely necessary to have the documentation open when looking at the result diagrams. Names like "OneMax", "LeadingOnes", "NQueens", or "Ising" may carry at least a bit more information and would make it easier to understand the diagrams. 

Also, having string function IDs would not break compatibility at all.
The existing files would all work as before.
Actually, you could even implement sorting the same way as before:
Simply test if all IDs are strings that can be converted to integers.
If so, sort by integer value.
Otherwise, sort alphabetically.

Moreover, having string function IDs would even increase the compatibility for future releases.
For example, maybe we discover along the way that problem F9 does not carry any useful information in all of our experiments and we want to replace it with something else.
Then, a string-based ID allows us to do that without any pain in a backwards-compatible way, while a numeric ID does not.
With numeric IDs, all we can do is add more problems, but we must never modify or replace any problem already added, because then the log files become ambiguous. 

Another important reason is this:
I have my own experimentation environment and I am currently working on a tool converting the output data from my types of experiments to IOHprofiler style data.
This is basically possible.
However, the mapping to numeric function IDs makes no sense here at all.
Since I cannot know in advance which benchmark problems are used by the user of my system, I also cannot assign reasonable numeric IDs in advance to the different problems.
This would mean that I would have to translate the IDs "as they come," i.e., the mapping of proper problem names such as "OneMax_10" or "MaxSat_uf050_025" to numeric function Ids would be entirely random and the user could not understand the results.
So if you want other researchers to use the platform, forcing them to translate their data to numeric problem IDs makes things much more complicated.

My suggestion would be to, first, allow in the IOHanalyzer string function and instance IDs.
This would, as said, not break compatibility.
In the future, one could then maybe also allow them in the IOHexperimenter.

Finally, having string-based IDs would make the use of "suite" superfluous.
The bbob problem IDs could be "bbob_f1...bbob_fn", the PBO problems could become "PBO_1...PBOn".
Actually, we could even replace them properly with "OneMax" and so on where applicable, because then we could compare experiments on the OneMax even if one of them was not done using PBO but someone else's code.
The same holds for the bbob names, they could become "Ackley" or "Schwefel_2_1" and what not.
But these would be ideas for the long run.

Last but not least: I have a secondary issue: From the online documentation, the interplay of function ID, dimension, and instance ID is unclear.

**Comment by thomasWeise** [comment]
I think string-based function IDs can be implemented with the above pull request.

**Comment by thomasWeise** [comment]
I have closed the original pull request #38, because I now add a more comprehensive one: #39.
#39 not just provides IOHanalyzer with the ability to handle string function IDs, but also fixes some minor issues with the server: The server could not load archives with more than one algorithm folder correctly and was ignoring the "maximization" field if provided in the user interface. It also had some minor issues when it could not detect the suite.

**Comment by wangronin** [comment]
Hi Thomas, 

Thank you so much for the great suggestions and their implementations! I believe this issue is resolved and hence I close it ;)

With kind regards,

Hao
