### ISSUE TITLE
Version should be displayed in the about page

### ISSUE THREAD

**Issue by nojhan** [IOHprofiler/IOHanalyzer#65]
The version of IOH analyzer should be displayed, in order to allow for reproducible research when using/citing IOH.
I suggest it should be in the "About" page.
Also, it may be useful to tag on github any version which would be deployed on iohprofiler.liacs.nl.

**Comment by Dvermetten** [comment]
Thank you for the suggestion, I have just implemented a version of this in #66

**Comment by nojhan** [comment]
Awesome!
