### ISSUE TITLE
Issue while exporting plots from local server

### ISSUE THREAD

**Issue by mariohevia** [IOHprofiler/IOHanalyzer#73]
Running on R the following commands:

```
library('IOHanalyzer')
runServer()
```

Later trying to download the sample plot from the settings in GUI results in the following error:

```
[64396:0730/094939.358955:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[64396:0730/094940.138883:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
|
done with code 1 in 247.61 ms - failed or incomplete task(s)
Warning: Error in processx::run: System command 'orca' failed, exit status: 1, stdout & stderr were printed
  [No stack trace available]
```

I have searched and the problem appears to be the use of gpu acceleration on electron/orca when the hardware is not available/compatible. It should be fixable by passing an extra argument when `orca` is called in the `save_plotly` function (line 354 and 357 in plot.R). 

The extra argument appears to be `more_args = "--disable-gpu"` or something similar.

**Comment by mariohevia** [comment]
After I wrote this I tried to run the following orca commands in R:
```
p <- plot_ly(z = ~volcano) %>% add_surface()
orca(p, "surface-plot.svg")
```
and got the same error. With the following code:
```
p <- plot_ly(z = ~volcano) %>% add_surface()
orca(p, "surface-plot.svg", more_args=c('--disable-gpu'))
```
I still got the error below, but the correct image is exported.
```
done with code 1 in 1.62 sec - failed or incomplete task(s)
Error in processx::run("orca", args, echo = TRUE, spinner = TRUE, ...) : 
  System command 'orca' failed, exit status: 1, stdout & stderr were printed
```

I guess this could be implemented into `plot.R` to see if this allows to download the plots even if an error is shown.

**Comment by Dvermetten** [comment]
Thanks a lot for notifying us of this issue. I have created a PR #74 which should provide a workaround.
Please let us know if this solves the issue for you.
